In [1]:
import numpy as np
import pandas as pd

In [2]:
gen_df = pd.read_csv("../general_table.csv")
gen_df.head()

,Date,USD (PM),Value,able_trade_gold,gold_growth_rate,bit_growth_rate,gip,bip,gir,bir,...,B,total property,gold_macd,bit_macd,gold_quantile,bit_quantile,gold_dif,bit_dif,gold_dea,bit_dea
0,2016-09-11,1324.60,621.65,0.0,0.000000,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000
1,2016-09-12,1324.60,609.67,1.0,0.000000,-0.019271,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,-1.529071,0.0,0.000000,0.000000,-0.955670,0.000000,-0.191134
2,2016-09-13,1323.65,610.92,1.0,-0.000717,0.002050,NaN,NaN,NaN,NaN,...,NaN,NaN,-0.121254,-2.244278,0.0,0.000000,-0.075783,-1.593808,-0.015157,-0.471669
3,2016-09-14,1321.75,608.82,1.0,-0.001435,-0.003437,NaN,NaN,NaN,NaN,...,NaN,NaN,-0.433127,-2.834341,0.0,0.000000,-0.285861,-2.243132,-0.069298,-0.825961
4,2016-09-15,1310.80,610.38,1.0,-0.008284,0.002562,NaN,NaN,NaN,NaN,...,NaN,NaN,-2.002242,-2.841428,0.4,0.333333,-1.320699,-2.601854,-0.319578,-1.181140

In [3]:
gen_df['gold_ma5'] = gen_df[gen_df.columns[1]].rolling(5).mean()
gen_df['bit_ma5'] = gen_df[gen_df.columns[2]].rolling(5).mean()
gen_df['gold_ma15'] = gen_df[gen_df.columns[1]].rolling(15).mean()
gen_df['bit_ma15'] = gen_df[gen_df.columns[2]].rolling(15).mean()

gen_df.head()

,Date,USD (PM),Value,able_trade_gold,gold_growth_rate,bit_growth_rate,gip,bip,gir,bir,...,gold_quantile,bit_quantile,gold_dif,bit_dif,gold_dea,bit_dea,gold_ma5,bit_ma5,gold_ma15,bit_ma15
0,2016-09-11,1324.60,621.65,0.0,0.000000,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
1,2016-09-12,1324.60,609.67,1.0,0.000000,-0.019271,NaN,NaN,NaN,NaN,...,0.0,0.000000,0.000000,-0.955670,0.000000,-0.191134,NaN,NaN,NaN,NaN
2,2016-09-13,1323.65,610.92,1.0,-0.000717,0.002050,NaN,NaN,NaN,NaN,...,0.0,0.000000,-0.075783,-1.593808,-0.015157,-0.471669,NaN,NaN,NaN,NaN
3,2016-09-14,1321.75,608.82,1.0,-0.001435,-0.003437,NaN,NaN,NaN,NaN,...,0.0,0.000000,-0.285861,-2.243132,-0.069298,-0.825961,NaN,NaN,NaN,NaN
4,2016-09-15,1310.80,610.38,1.0,-0.008284,0.002562,NaN,NaN,NaN,NaN,...,0.4,0.333333,-1.320699,-2.601854,-0.319578,-1.181140,1321.08,612.288,NaN,NaN

In [7]:
gen_df['gold_ma5_bias'] = 100 *(gen_df['USD (PM)'] - gen_df['gold_ma5']) / gen_df['gold_ma5']
gen_df['gold_ma15_bias'] = 100 *(gen_df['USD (PM)'] - gen_df['gold_ma15']) / gen_df['gold_ma15']

gen_df['bit_ma5_bias'] = 100 * (gen_df['Value'] - gen_df['bit_ma5']) / gen_df['bit_ma5']
gen_df['bit_ma15_bias'] = 100 * (gen_df['Value'] - gen_df['bit_ma15']) / gen_df['bit_ma15']

gen_df.head()

,Date,USD (PM),Value,able_trade_gold,gold_growth_rate,bit_growth_rate,gip,bip,gir,bir,...,gold_dea,bit_dea,gold_ma5,bit_ma5,gold_ma15,bit_ma15,gold_ma5_bias,gold_ma15_bias,bit_ma5_bias,bit_ma15_bias
0,2016-09-11,1324.60,621.65,0.0,0.000000,0.000000,NaN,NaN,NaN,NaN,...,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-09-12,1324.60,609.67,1.0,0.000000,-0.019271,NaN,NaN,NaN,NaN,...,0.000000,-0.191134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-09-13,1323.65,610.92,1.0,-0.000717,0.002050,NaN,NaN,NaN,NaN,...,-0.015157,-0.471669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-09-14,1321.75,608.82,1.0,-0.001435,-0.003437,NaN,NaN,NaN,NaN,...,-0.069298,-0.825961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-09-15,1310.80,610.38,1.0,-0.008284,0.002562,NaN,NaN,NaN,NaN,...,-0.319578,-1.181140,1321.08,612.288,NaN,NaN,-0.778151,NaN,-0.311618,NaN

In [8]:
gen_df.columns

Index(['Date', 'USD (PM)', 'Value', 'able_trade_gold', 'gold_growth_rate',
       'bit_growth_rate', 'gip', 'bip', 'gir', 'bir', 'C', 'G', 'B',
       'total property', 'gold_macd', 'bit_macd', 'gold_quantile',
       'bit_quantile', 'gold_dif', 'bit_dif', 'gold_dea', 'bit_dea',
       'gold_ma5', 'bit_ma5', 'gold_ma15', 'bit_ma15', 'gold_ma5_bias',
       'gold_ma15_bias', 'bit_ma5_bias', 'bit_ma15_bias'],
      dtype='object')

In [9]:
gen_df['gold_growth_rate'] = gen_df['gold_growth_rate'] * 100
gen_df['bit_growth_rate'] = gen_df['bit_growth_rate'] * 100

gen_df['gold_quantile'] = gen_df['gold_quantile'] * 100
gen_df['bit_quantile'] = gen_df['bit_quantile'] * 100
gen_df.to_csv("../bias-means-table.csv")

In [10]:
gen_df.head(25)

,Date,USD (PM),Value,able_trade_gold,gold_growth_rate,bit_growth_rate,gip,bip,gir,bir,...,gold_dea,bit_dea,gold_ma5,bit_ma5,gold_ma15,bit_ma15,gold_ma5_bias,gold_ma15_bias,bit_ma5_bias,bit_ma15_bias
0,2016-09-11,1324.60,621.65,0.0,0.000000,0.000000,NaN,NaN,NaN,NaN,...,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-09-12,1324.60,609.67,1.0,0.000000,-1.927129,NaN,NaN,NaN,NaN,...,0.000000,-0.191134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-09-13,1323.65,610.92,1.0,-0.071720,0.205029,NaN,NaN,NaN,NaN,...,-0.015157,-0.471669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-09-14,1321.75,608.82,1.0,-0.143542,-0.343744,NaN,NaN,NaN,NaN,...,-0.069298,-0.825961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-09-15,1310.80,610.38,1.0,-0.828447,0.256233,NaN,NaN,NaN,NaN,...,-0.319578,-1.181140,1321.08,612.288,NaN,NaN,-0.778151,NaN,-0.311618,NaN
5,2016-09-16,1308.35,609.11,1.0,-0.186909,-0.208067,NaN,NaN,NaN,NaN,...,-0.718034,-1.535825,1317.83,609.780,NaN,NaN,-0.719364,NaN,-0.109876,NaN
6,2016-09-17,1308.35,607.04,0.0,0.000000,-0.339840,NaN,NaN,NaN,NaN,...,-1.186840,-1.901132,1314.58,609.254,NaN,NaN,-0.473916,NaN,-0.363395,NaN
7,2016-09-18,1308.35,611.58,0.0,0.000000,0.747891,NaN,NaN,NaN,NaN,...,-1.672460,-2.177181,1311.52,609.386,NaN,NaN,-0.241704,NaN,0.360035,NaN
8,2016-09-19,1314.85,610.19,1.0,0.496809,-0.227280,NaN,NaN,NaN,NaN,...,-2.035644,-2.400029,1310.14,609.660,NaN,NaN,0.359504,NaN,0.086934,NaN
9,2016-09-20,1313.80,608.66,1.0,-0.079857,-0.250742,NaN,NaN,NaN,NaN,...,-2.315163,-2.596789,1310.74,609.316,NaN,NaN,0.233456,NaN,-0.107662,NaN
10,2016-09-21,1326.10,598.88,1.0,0.936216,-1.606808,NaN,NaN,NaN,NaN,...,-2.326074,-2.916998,1314.29,607.270,NaN,NaN,0.898584,NaN,-1.381593,NaN
11,2016-09-22,1339.10,597.42,1.0,0.980318,-0.243788,NaN,NaN,NaN,NaN,...,-1.955344,-3.314443,1320.44,605.346,NaN,NaN,1.413165,NaN,-1.309334,NaN
12,2016-09-23,1338.65,594.08,1.0,-0.033605,-0.559071,NaN,NaN,NaN,NaN,...,-1.367567,-3.785196,1326.50,601.846,NaN,NaN,0.915944,NaN,-1.290363,NaN
13,2016-09-24,1338.65,603.88,0.0,0.000000,1.649609,NaN,NaN,NaN,NaN,...,-0.671444,-4.112238,1331.26,600.584,NaN,NaN,0.555113,NaN,0.548799,NaN
14,2016-09-25,1338.65,601.74,0.0,0.000000,-0.354375,NaN,NaN,NaN,NaN,...,0.057626,-4.356832,1336.23,599.200,1322.683333,606.934667,0.181107,1.207142,0.423899,-0.855886
15,2016-09-26,1340.50,598.98,1.0,0.138199,-0.458670,NaN,NaN,NaN,NaN,...,0.798513,-4.571031,1339.11,599.220,1323.743333,605.423333,0.103800,1.265855,-0.040052,-1.064269
16,2016-09-27,1327.00,605.96,1.0,-1.007087,1.165314,NaN,NaN,NaN,NaN,...,1.290762,-4.633169,1336.69,600.928,1323.903333,605.176000,-0.724925,0.233904,0.837372,0.129549
17,2016-09-28,1322.50,605.67,1.0,-0.339111,-0.047858,NaN,NaN,NaN,NaN,...,1.526629,-4.590809,1333.46,603.246,1323.826667,604.826000,-0.821922,-0.100215,0.401826,0.139544
18,2016-09-29,1318.10,603.85,1.0,-0.332703,-0.300494,NaN,NaN,NaN,NaN,...,1.515758,-4.503745,1329.35,603.240,1323.583333,604.494667,-0.846278,-0.414279,0.101121,-0.106646
19,2016-09-30,1322.50,609.39,1.0,0.333814,0.917446,NaN,NaN,NaN,NaN,...,1.417550,-4.294574,1326.12,604.770,1324.363333,604.428667,-0.272977,-0.140697,0.763927,0.820830
20,2016-10-01,1322.50,614.82,0.0,0.000000,0.891055,NaN,NaN,NaN,NaN,...,1.266518,-3.923412,1322.52,607.938,1325.306667,604.809333,-0.001512,-0.211775,1.132023,1.655177
21,2016-10-02,1322.50,612.98,0.0,0.000000,-0.299275,NaN,NaN,NaN,NaN,...,1.087408,-3.490588,1321.62,609.342,1326.250000,605.205333,0.066585,-0.282752,0.597037,1.284633
22,2016-10-03,1313.30,611.85,1.0,-0.695652,-0.184345,NaN,NaN,NaN,NaN,...,0.750830,-3.051879,1319.78,610.578,1326.580000,605.223333,-0.490991,-1.001070,0.208327,1.094913
23,2016-10-04,1283.30,609.62,1.0,-2.284322,-0.364468,NaN,NaN,NaN,NaN,...,-0.147146,-2.661100,1312.82,611.732,1324.476667,605.185333,-2.248595,-3.108901,-0.345249,0.732778
24,2016-10-05,1269.40,607.18,1.0,-1.083145,-0.400249,NaN,NaN,NaN,NaN,...,-1.571353,-2.353712,1302.20,611.290,1321.516667,605.086667,-2.518814,-3.943701,-0.672349,0.345956

In [11]:
gen_df.columns

Index(['Date', 'USD (PM)', 'Value', 'able_trade_gold', 'gold_growth_rate',
       'bit_growth_rate', 'gip', 'bip', 'gir', 'bir', 'C', 'G', 'B',
       'total property', 'gold_macd', 'bit_macd', 'gold_quantile',
       'bit_quantile', 'gold_dif', 'bit_dif', 'gold_dea', 'bit_dea',
       'gold_ma5', 'bit_ma5', 'gold_ma15', 'bit_ma15', 'gold_ma5_bias',
       'gold_ma15_bias', 'bit_ma5_bias', 'bit_ma15_bias'],
      dtype='object')

In [20]:
# 黄金15日震荡
# 比特币5日震荡
def get_mean_growth_positive(rb, n):
    return rb[rb > 0].sum() / n

def get_mean_growth_negative(rb, n):
    return  - rb[rb < 0].sum() / n

def get_rsi(positive, negative):
    return (positive / (positive + negative)) * 100    

pg = gen_df['gold_growth_rate'].rolling(15).apply(get_mean_growth_positive, args=(15, ))
ng = gen_df['gold_growth_rate'].rolling(15).apply(get_mean_growth_negative, args=(15, ))

pb = gen_df['bit_growth_rate'].rolling(5).apply(get_mean_growth_positive, args=(5, ))
nb = gen_df['bit_growth_rate'].rolling(5).apply(get_mean_growth_negative, args=(5, ))

gen_df['gold_rsi_15'] = get_rsi(pg, ng)
gen_df['bit_rsi_5'] = get_rsi(pb, nb)

In [21]:
gen_df.head(20)

,Date,USD (PM),Value,able_trade_gold,gold_growth_rate,bit_growth_rate,gip,bip,gir,bir,...,gold_ma5,bit_ma5,gold_ma15,bit_ma15,gold_ma5_bias,gold_ma15_bias,bit_ma5_bias,bit_ma15_bias,gold_rsi_15,bit_rsi_5
0,2016-09-11,1324.60,621.65,0.0,0.000000,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-09-12,1324.60,609.67,1.0,0.000000,-1.927129,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-09-13,1323.65,610.92,1.0,-0.071720,0.205029,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-09-14,1321.75,608.82,1.0,-0.143542,-0.343744,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-09-15,1310.80,610.38,1.0,-0.828447,0.256233,NaN,NaN,NaN,NaN,...,1321.08,612.288,NaN,NaN,-0.778151,NaN,-0.311618,NaN,NaN,16.882849
5,2016-09-16,1308.35,609.11,1.0,-0.186909,-0.208067,NaN,NaN,NaN,NaN,...,1317.83,609.780,NaN,NaN,-0.719364,NaN,-0.109876,NaN,NaN,15.688113
6,2016-09-17,1308.35,607.04,0.0,0.000000,-0.339840,NaN,NaN,NaN,NaN,...,1314.58,609.254,NaN,NaN,-0.473916,NaN,-0.363395,NaN,NaN,34.094002
7,2016-09-18,1308.35,611.58,0.0,0.000000,0.747891,NaN,NaN,NaN,NaN,...,1311.52,609.386,NaN,NaN,-0.241704,NaN,0.360035,NaN,NaN,52.966430
8,2016-09-19,1314.85,610.19,1.0,0.496809,-0.227280,NaN,NaN,NaN,NaN,...,1310.14,609.660,NaN,NaN,0.359504,NaN,0.086934,NaN,NaN,56.433312
9,2016-09-20,1313.80,608.66,1.0,-0.079857,-0.250742,NaN,NaN,NaN,NaN,...,1310.74,609.316,NaN,NaN,0.233456,NaN,-0.107662,NaN,NaN,42.162748
10,2016-09-21,1326.10,598.88,1.0,0.936216,-1.606808,NaN,NaN,NaN,NaN,...,1314.29,607.270,NaN,NaN,0.898584,NaN,-1.381593,NaN,NaN,23.573739
11,2016-09-22,1339.10,597.42,1.0,0.980318,-0.243788,NaN,NaN,NaN,NaN,...,1320.44,605.346,NaN,NaN,1.413165,NaN,-1.309334,NaN,NaN,24.309735
12,2016-09-23,1338.65,594.08,1.0,-0.033605,-0.559071,NaN,NaN,NaN,NaN,...,1326.50,601.846,NaN,NaN,0.915944,NaN,-1.290363,NaN,NaN,0.000000
13,2016-09-24,1338.65,603.88,0.0,0.000000,1.649609,NaN,NaN,NaN,NaN,...,1331.26,600.584,NaN,NaN,0.555113,NaN,0.548799,NaN,NaN,38.273837
14,2016-09-25,1338.65,601.74,0.0,0.000000,-0.354375,NaN,NaN,NaN,NaN,...,1336.23,599.200,1322.683333,606.934667,0.181107,1.207142,0.423899,-0.855886,64.228676,37.375160
15,2016-09-26,1340.50,598.98,1.0,0.138199,-0.458670,NaN,NaN,NaN,NaN,...,1339.11,599.220,1323.743333,605.423333,0.103800,1.265855,-0.040052,-1.064269,65.497679,50.516083
16,2016-09-27,1327.00,605.96,1.0,-1.007087,1.165314,NaN,NaN,NaN,NaN,...,1336.69,600.928,1323.903333,605.176000,-0.724925,0.233904,0.837372,0.129549,52.043513,67.229457
17,2016-09-28,1322.50,605.67,1.0,-0.339111,-0.047858,NaN,NaN,NaN,NaN,...,1333.46,603.246,1323.826667,604.826000,-0.821922,-0.100215,0.401826,0.139544,49.351888,76.579341
18,2016-09-29,1318.10,603.85,1.0,-0.332703,-0.300494,NaN,NaN,NaN,NaN,...,1329.35,603.240,1323.583333,604.494667,-0.846278,-0.414279,0.101121,-0.106646,47.609961,50.084193
19,2016-09-30,1322.50,609.39,1.0,0.333814,0.917446,NaN,NaN,NaN,NaN,...,1326.12,604.770,1324.363333,604.428667,-0.272977,-0.140697,0.763927,0.820830,59.312987,72.073277

In [22]:
gen_df.to_csv("../rsi-table.csv")

In [25]:
gen_df['gold_growth'] = 0
gen_df['bit_growth'] = 0
for i in gen_df.index[1:]:
    gen_df['gold_growth'].iloc[i] = gen_df['USD (PM)'].iloc[i] - gen_df['USD (PM)'].iloc[i - 1]
    gen_df['bit_growth'].iloc[i] = gen_df['Value'].iloc[i] - gen_df['Value'].iloc[i - 1]

D:\Anaconda\envs\deeplab\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [27]:
# 盈亏比
gen_df['gold_pl_rate'] = 0
gen_df['bit_pl_rate'] = 0
for i in gen_df.index[1:]:
    prev_data_gold = gen_df['gold_growth'].iloc[:i + 1]
    gen_df['gold_pl_rate'].iloc[i] = prev_data_gold[prev_data_gold >
                                                    0].mean() / prev_data_gold[prev_data_gold < 0].mean()

    prev_data_bit = gen_df['bit_growth'].iloc[:i + 1]
    gen_df['bit_pl_rate'].iloc[i] = prev_data_bit[prev_data_bit >
                                                    0].mean() / prev_data_bit[prev_data_bit < 0].mean()

D:\Anaconda\envs\deeplab\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [28]:
gen_df.head(20)

,Date,USD (PM),Value,able_trade_gold,gold_growth_rate,bit_growth_rate,gip,bip,gir,bir,...,gold_ma5_bias,gold_ma15_bias,bit_ma5_bias,bit_ma15_bias,gold_rsi_15,bit_rsi_5,gold_growth,bit_growth,gold_pl_rate,bit_pl_rate
0,2016-09-11,1324.60,621.65,0.0,0.000000,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.000000,0.000000
1,2016-09-12,1324.60,609.67,1.0,0.000000,-1.927129,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00,-11.98,NaN,NaN
2,2016-09-13,1323.65,610.92,1.0,-0.071720,0.205029,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-0.95,1.25,NaN,-0.104341
3,2016-09-14,1321.75,608.82,1.0,-0.143542,-0.343744,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-1.90,-2.10,NaN,-0.177557
4,2016-09-15,1310.80,610.38,1.0,-0.828447,0.256233,NaN,NaN,NaN,NaN,...,-0.778151,NaN,-0.311618,NaN,NaN,16.882849,-10.95,1.56,NaN,-0.199574
5,2016-09-16,1308.35,609.11,1.0,-0.186909,-0.208067,NaN,NaN,NaN,NaN,...,-0.719364,NaN,-0.109876,NaN,NaN,15.688113,-2.45,-1.27,NaN,-0.274593
6,2016-09-17,1308.35,607.04,0.0,0.000000,-0.339840,NaN,NaN,NaN,NaN,...,-0.473916,NaN,-0.363395,NaN,NaN,34.094002,0.00,-2.07,NaN,-0.322618
7,2016-09-18,1308.35,611.58,0.0,0.000000,0.747891,NaN,NaN,NaN,NaN,...,-0.241704,NaN,0.360035,NaN,NaN,52.966430,0.00,4.54,NaN,-0.562572
8,2016-09-19,1314.85,610.19,1.0,0.496809,-0.227280,NaN,NaN,NaN,NaN,...,0.359504,NaN,0.086934,NaN,NaN,56.433312,6.50,-1.39,-1.600000,-0.651249
9,2016-09-20,1313.80,608.66,1.0,-0.079857,-0.250742,NaN,NaN,NaN,NaN,...,0.233456,NaN,-0.107662,NaN,NaN,42.162748,-1.05,-1.53,-1.878613,-0.722714
10,2016-09-21,1326.10,598.88,1.0,0.936216,-1.606808,NaN,NaN,NaN,NaN,...,0.898584,NaN,-1.381593,NaN,NaN,23.573739,12.30,-9.78,-2.716763,-0.569389
11,2016-09-22,1339.10,597.42,1.0,0.980318,-0.243788,NaN,NaN,NaN,NaN,...,1.413165,NaN,-1.309334,NaN,NaN,24.309735,13.00,-1.46,-3.063584,-0.620646
12,2016-09-23,1338.65,594.08,1.0,-0.033605,-0.559071,NaN,NaN,NaN,NaN,...,0.915944,NaN,-1.290363,NaN,NaN,0.000000,-0.45,-3.34,-3.583099,-0.631443
13,2016-09-24,1338.65,603.88,0.0,0.000000,1.649609,NaN,NaN,NaN,NaN,...,0.555113,NaN,0.548799,NaN,NaN,38.273837,0.00,9.80,-3.583099,-1.105026
14,2016-09-25,1338.65,601.74,0.0,0.000000,-0.354375,NaN,NaN,NaN,NaN,...,0.181107,1.207142,0.423899,-0.855886,64.228676,37.375160,0.00,-2.14,-3.583099,-1.156908
15,2016-09-26,1340.50,598.98,1.0,0.138199,-0.458670,NaN,NaN,NaN,NaN,...,0.103800,1.265855,-0.040052,-1.064269,65.497679,50.516083,1.85,-2.76,-2.843662,-1.184392
16,2016-09-27,1327.00,605.96,1.0,-1.007087,1.165314,NaN,NaN,NaN,NaN,...,-0.724925,0.233904,0.837372,0.129549,52.043513,67.229457,-13.50,6.98,-1.884400,-1.333149
17,2016-09-28,1322.50,605.67,1.0,-0.339111,-0.047858,NaN,NaN,NaN,NaN,...,-0.821922,-0.100215,0.401826,0.139544,49.351888,76.579341,-4.50,-0.29,-1.882517,-1.443829
18,2016-09-29,1318.10,603.85,1.0,-0.332703,-0.300494,NaN,NaN,NaN,NaN,...,-0.846278,-0.414279,0.101121,-0.106646,47.609961,50.084193,-4.40,-1.82,-1.885741,-1.496256
19,2016-09-30,1322.50,609.39,1.0,0.333814,0.917446,NaN,NaN,NaN,NaN,...,-0.272977,-0.140697,0.763927,0.820830,59.312987,72.073277,4.40,5.54,-1.705853,-1.533150

In [29]:
gen_df.to_csv('../盈亏比.csv')